name: KEFSKI Photo
favicon: null
layout_spectrum: 0.7995858187787235
typography_spectrum: 0.5146587425842881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9179649397265166
  lightness: 0.9485543500632048
  saturation: 0.4057362084276974
  rhythmicContrast: 0.8013209789060056
purpose: []
