name: KEFSKI Photo
favicon: null
layout_spectrum: 0.18185
typography_spectrum: 0.60273
title: KEFSKI Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcbc5f'
    - '#ff0000'
    - '#000000'
    - '#7f7f00'
    - '#ffffff'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
